name: Java CI

on:
  push:
    branches:
      - 'test'
      - 'develop'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  test:
    name: Test - Units & Integrations
    runs-on: macos-latest